In [2]:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)


[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [3]:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)


Shape: (7,)
Data type: float64
Number of elements: 7


In [4]:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_f = (temperatures_w1 * 9/5) + 32
max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)
print("Temperatures in Fahrenheit:", temperatures_f)
print("Maximum temperature (°C):", max_temp)
print("Minimum temperature (°C):", min_temp)
print("Mean temperature (°C):", mean_temp)


Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temperature (°C): 26.1
Minimum temperature (°C): 20.8
Mean temperature (°C): 23.542857142857144


In [5]:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
first_three_days = temperatures_w1[:3]
weekend_temps = temperatures_w1[-2:]
middle_three_days = temperatures_w1[2:5]
print("First three days temperatures:", first_three_days)
print("Weekend temperatures:", weekend_temps)
print("Middle three days temperatures:", middle_three_days)


First three days temperatures: [22.5 25.3 20.8]
Weekend temperatures: [24.8 21.9]
Middle three days temperatures: [20.8 23.4 26.1]


In [6]:
import numpy as np
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])
print(temperatures)


[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [7]:
import numpy as np
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)
week1_temps = temperatures[0]
week2_temps = temperatures[1]
weekend_temps = temperatures[:, -2:]
print("\nWeek 1 temperatures:", week1_temps)
print("Week 2 temperatures:", week2_temps)
print("Weekend temperatures (both weeks):", weekend_temps)


Shape: (2, 7)
Data type: float64
Total number of elements: 14

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend temperatures (both weeks): [[24.8 21.9]
 [22.8 20.1]]


In [8]:
import pandas as pd
marks = pd.Series(
    data=[95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [9]:
import pandas as pd
marks = pd.Series(
    data=[95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
first_rank_mark = marks[0]
top_3_marks = marks.loc[['Rank1', 'Rank2', 'Rank3']]
third_rank_mark = marks.iloc[2]
above_90 = marks[marks > 90]
print("Mark of 1st rank student:", first_rank_mark)
print("\nTop 3 ranks marks:\n", top_3_marks)
print("\nMark of 3rd rank student:", third_rank_mark)
print("\nRanks with marks greater than 90:\n", above_90)


Mark of 1st rank student: 95

Top 3 ranks marks:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of 3rd rank student: 89

Ranks with marks greater than 90:
 Rank1    95
Rank2    92
dtype: int64


/tmp/ipython-input-1763073321.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  first_rank_mark = marks[0]


In [10]:
import pandas as pd
marks = pd.Series(
    data=[95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
marks.loc['Rank1'] = 100
marks = marks.drop('Rank5')
cgpa = marks / 10
print("Updated Marks Series:\n", marks)
print("\nCGPA Series:\n", cgpa)


Updated Marks Series:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA Series:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [11]:
import pandas as pd
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [12]:
import pandas as pd
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print("Head:\n", transactions.head())
print("\nTail:\n", transactions.tail())
print("\nShape:", transactions.shape)
print("\nColumn Names:", transactions.columns)
print("\nData Types:\n", transactions.dtypes)
print("\nProductCategory and Amount columns:\n",
      transactions[['ProductCategory', 'Amount']])
print("\nLast 3 columns:\n", transactions.iloc[:, -3:])
north_high_amount = transactions[
    (transactions['Region'] == 'North') & (transactions['Amount'] > 200)
]
print("\nTransactions from North with Amount > 200:\n", north_high_amount)
print("\nProductCategory value counts:\n",
      transactions['ProductCategory'].value_counts())
print("\nUnique Regions:\n", transactions['Region'].unique())
print("\nMean Amount by Region:\n",
      transactions.groupby('Region')['Amount'].mean())


Head:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)

Column Names: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

Data Types:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

ProductCategory and Amount columns:
   ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     45

In [13]:
import pandas as pd
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions['Discount'] = transactions['Amount'] * 0.10
transactions = transactions[transactions['TransactionID'] != 109]
transactions.drop(columns='Discount', inplace=True)
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
